stages:
  - build

build_jar:
  stage: build
  only:
    - main
  script:
    - echo "Building JAR file..."
    - mvn clean package
    - mkdir -p build
    - cp target/*.jar build/
  artifacts:
    paths:
      - build/*.jar
    expire_in: 1 day
